[project]
name = "fastapi-app"
version = "0.1.0"
description = "A FastAPI application with Next.js frontend"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
    "pydantic>=2.9.2",
]

[dependency-groups]
dev = []
