"on":
    push:
        branches:
            - main
name: Deploy to my-app
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply
              env:
                PORTER_APP_NAME: my-app
                PORTER_CLUSTER: "2"
                PORTER_DEPLOYMENT_TARGET_ID: e7e8b9f0-a8a4-4d97-915f-86f96e82cbb8
                PORTER_HOST: https://witt.withporter.run
                PORTER_PROJECT: "1"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1068546388 }}
